import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const yellowtail = localFont({
  src: "../../public/fonts/Yellowtail-Regular.ttf",
  variable: "--font-yellowtail",
  display: "swap",
});

const fjallaOne = localFont({
  src: "../../public/fonts/FjallaOne-Regular.ttf",
  variable: "--font-fjalla-one",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${yellowtail.variable} ${fjallaOne.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
